### PR TITLE
Open favorite Web page in other browser window

### PR DESCRIPTION
**Pull request by EduardoJimenez**
Many sites now do not allow to be embedded in iframes

### CODE REVIEW

**Comment by joebordes** [comment]
You have implemented an "all or nothing" solution.
What I had in mind was to detect if the website we are trying to load has X-Frame-Options set to deny and, in that case, show a message something like:

"The website you have indicated has blocked loading inside another webpage so you will have to open it in a new window/tab. Please click here if you want to access the site."

If the site is not blocked simply do what we do now.

That would require doing this:
https://stackoverflow.com/questions/21263418/detect-x-frame-options?rq=1

create a function to call this for the URL and act accordingly.

What do you think?

**Comment by ecrmweb** [comment]
Good solution.

Thanks!

*Ranieri Slemer*


“CRM é uma estratégia para o crescimento e sobrevivência empresarial”.


2017-01-12 6:53 GMT-02:00 Joe Bordes <notifications@github.com>:

**Comment by EduardoJimenez** [comment]
Can we safely assume that the curl module will be available in our installations?

If that is so, then I will include some logic based on the link given, and if it works, restore the iframe for the cases allowed.

Believe me, I tried to tap into the iframe properties to detect no page, but without any success.

**Comment by joebordes** [comment]
Yes, you can count in having cURL installed. The application uses it in some places. We even have a high level interface for it:

vtlib/Vtiger/Net/Client.php: Vtiger_Net_Client

I can imagine, it happens to me every day :-)

Have a nice weekend

**Comment by EduardoJimenez** [comment]
I have made a commit with the definitive fix, have you received it?

**Comment by joebordes** [comment]
There are two PRs here about this issue. I see them both and will get around to testing and integrating them shortly.
I'll get back to you soon

**Pull request merged**
