### PR TITLE
fix(Listviewcolumnsearch) hardcode mincharstosearch to even make the …

### PR DESCRIPTION
**Pull request by Luke1982**
…autocomplete work at all, related to #688

This PR is live and needs updates

### CODE REVIEW

**Comment by joebordes** [comment]
couldn't we get the current value of the global variable and put it there instead of "1"?  wouldn't that solve the problem?

**Comment by Luke1982** [comment]
Yes it would, forgot we had that. Let me alter the PR

**Comment by Luke1982** [comment]
Just checking the list of available GV's but I can't find one that specifically controls the min chars to search

**Comment by joebordes** [comment]
sorry, my bad, I am mixing the Global Search autocomplete with the list view one. You are right there is no global variable and the autocomplete map has it hardcoded too. So, besides adding the GV which, if you can't it is ok, at least, set the default value to the same default value [we have in the autocomplete map (3)](https://github.com/tsolucio/corebos/blob/master/modules/cbMap/processmap/GlobalSearchAutocomplete.php#L46) and I will accept the PR

**Comment by Luke1982** [comment]
I think I'll add the GV. Since this PR is related to issue #688 I've added some more fixes for columnsearch in reference fields. I also want to style the results list so that it's as wide as the input it fills. Then I think I've solved all the funkyness

**Comment by joebordes** [comment]
thanks!

**Pull request merged**
