### PR TITLE
Fix regular main search

### LINKED ISSUE #702: Main search doesn't work when other autcompletes are active
This seems to be the case when you search something that the main search could not process into an autocomplete suggestion

### PR DESCRIPTION
**Pull request by Luke1982**
Fixes #702

### CODE REVIEW

**Comment by Luke1982** [comment]
Travis failed on the double boolean casting, don't know if that's really a problem?

**Comment by joebordes** [comment]
I would prefer to eliminate that double boolean. I really don't understand what it is doing but I can imagine that it is some edge functionality of javascript that converts the value to boolean in case it isn't and that may break two years from now.
It makes it harder to read and maintain the code as you are presuming some advanced knowledge of JS that many may not have.
Can you change the condition to something more understandable?

**Comment by joebordes** [comment]
manually merged this one since I had to update the service worker also and I tried to convert the double boolean to an equivalent conditional with no sucess: JS is a mess

Thanks!

**Comment by Luke1982** [comment]
I love the double boolean, it's simply a way of saying 'is anything but false'. I don't know the implications of the perils that could happen, but maybe there's something I don't know yet. Anyway, you could just replace it with
```javascript
if (variable !== false)
```

**Comment by Luke1982** [comment]
> manually merged this one since I had to update the service worker also and I tried to convert the double boolean to an equivalent conditional with no sucess: JS is a mess
> 
> Thanks!

About the serviceworker, I updated it but you'd like it in a different maner?

**Comment by joebordes** [comment]
you updated the service worker correctly, it was just that I had to update it also due to the fix of moving the inventory lines and since I was already testing your change I decided to update your change and mine in one commit

this PR was totally correct: no worries

**Pull request closed without merging**
