### PR TITLE
(feat) Make "getRelatedRecords" return creator's first and last name

### PR DESCRIPTION
**Pull request by Luke1982**

### CODE REVIEW

**Comment by joebordes** [comment]
Looks good.
How about doing the same for smownerid (owner_firstname and owner_lastname)?

**Comment by Luke1982** [comment]
No problem, give me a sec.

**Comment by Luke1982** [comment]
Tested and works for owner as well.

**Comment by joebordes** [comment]
Perfect.
Just one comment on the commit message for the next ones you create: the format is detailed here http://corebos.org/documentation/doku.php?id=en:devel:commitguidelines

In this case it would be:

feat(Webservice) {message}

Thanks!!

**Comment by Luke1982** [comment]
Ah yeah thanks, I knew that but forgot...

**Pull request merged**
