### PR TITLE
Don't do multicurrency autocomplete in PO's, fixes #473

### LINKED ISSUE #473: Products with multiple currencies don't fill costprice in PO's
https://github.com/tsolucio/corebos/blob/b780d815f6bb00c62783011ee9dab714d1958863/include/js/Inventory.js#L1869

This lines needs another check for the gVTModule not being PurchaseOrder

### PR DESCRIPTION
**Pull request by Luke1982**

### CODE REVIEW

**Comment by Luke1982** [comment]
When you would do an autocomplete search for a product in a PO and that product has multicurrency activated, the selling price would be filled. This fixes it so that in PO's, the multicurrency bit it ignored.

**Comment by joebordes** [comment]
why ignore multicurrency?

**Comment by Luke1982** [comment]
Because we switched to costprice entirely for PO's and that field doesn't support it. The way it is now is that the autocomplete uses costprice when MC is not active on the product but uses sellingprice when it is.

**Comment by joebordes** [comment]
got it, thanks

**Pull request merged**
