### PR TITLE
fix(ProductServiceAC) Don't show vendor and mfr part no when they're …

### PR DESCRIPTION
**Pull request by Luke1982**
…disabled

What the problem was: if you disabled either the vendor of manufacturer part no., you would still see them in the results.

### CODE REVIEW

**Comment by Luke1982** [comment]
What this does not solve is: when you don't setup a businessmap that controls the searchfields, the manufacturer and vendor part no.'s will still be searched in, even though they might not be active.

**Comment by joebordes** [comment]
shouldn't we solve this by not adding the non-accessible fields to the $productsearchfields array?

``` PHP
	$productsearchfields = array('productname');
	if (getFieldVisibilityPermission('Products', $current_user->id, 'mfr_part_no') == '0') {
		$productsearchfields[] = 'mfr_part_no';
	}
	if (getFieldVisibilityPermission('Products', $current_user->id, 'vendor_part_no') == '0') {
		$productsearchfields[] = 'vendor_part_no';
	}
```

and then the implications that has in the rest of the function and code

**Comment by Luke1982** [comment]
Well what I set out to do was try and prevent additional queries, or at least (since I do setup subqueries) prevent new DB connections. But yes I do think we should just prevent looking in the fields as well when they're deactivated since they are hardcoded fields when you don't override them with a business map. Let me try and rework the problem.

**Comment by Luke1982** [comment]
@joebordes OK this is now preventing the fields from showing up under any circumstance, regardless of if the field in selected through a businessmap or not.

**Comment by joebordes** [comment]
looks ok.
shouldn't we add `getFieldVisibilityPermission` on the fields in the Map also?

**Comment by Luke1982** [comment]
I suppose so. We could walk through both products and services searchfields arrays (the default one is overwritten when you use a businessmap) and unset the keys based on the visibility/permission. For the part_no fields we should set the special `##FIELDDISABLED##` value so that the frontend knows to disable showing those fields.

In the future you'd want to customize the result box and do the `##FIELDDISABLED##` trick for all fields that are requested but not active or permitted.

**Comment by joebordes** [comment]
thanks!

**Pull request merged**
