### PR TITLE
feat(Utilities) Allow getting image information for a record through …

### PR DESCRIPTION
**Pull request by Luke1982**
…an AJAX call

### CODE REVIEW

**Comment by Luke1982** [comment]
Example, the URL
`index.php?module=Utilities&action=UtilitiesAjax&file=ExecuteFunctions&functiontocall=getImageInfoFor&record=2617`
Will get you the image info on record 2617, if any

**Comment by Luke1982** [comment]
I notice this only gets the latest image related to that record when you try and get images from products.

**Comment by Luke1982** [comment]
@joebordes Could you take a look at this? I'd like it to return multiple images when multiple are available

**Comment by joebordes** [comment]
well, the correct thing to do is add image fields on the module, not inside the special product multi-image field, but individual images with a name and a purpose. For example:

- home page image
- EAN image (which can be generated by a workflow)
- right side view
- left side view
...

not all bundled together inside one field

is that a solution for your use case?

**Comment by Luke1982** [comment]
Well yes, that would be a much better way of doing things all together. Installations that do have multiple images on a product through the 'old' method would have to convert them to multiple fields, but that seems like a better way to do things so need break that egg to make the omelet I guess.

**Comment by joebordes** [comment]
just to be clear: this works already, you don't have to do anything, getrecordimages returns all the image fields, the only field not supported is the special (non-standard) field in products which returns only one of the images in the field.

**Comment by Luke1982** [comment]
Exactly. So if you want to get all the images for a product: they need to be on separate fields.

**Pull request merged**
