### PR TITLE
Underscore not working in search

### PR DESCRIPTION
**Pull request by maliknajjar**
When trying to search the string "_text" it will consider the underscore as a wildcard that represents any value. in order to fix this we need to escape the underscore in the string.

### CODE REVIEW

**Comment by maliknajjar** [comment]
@joebordes yes .. actually, I think maybe its better to even escape the $value variable itself. because we should not give the user the ability to use the underscore wildcard. and I don't think that query generator use it anywhere. wdyt?

**Comment by joebordes** [comment]
> @joebordes yes .. actually, I think maybe its better to even escape the $value variable itself. because we should not give the user the ability to use the underscore wildcard. and I don't think that query generator use it anywhere. wdyt?

I don't agree because when they do an exact search we will want to have that underscore. I mean if someone is using the `equals` or `not equals`, I think we need to permit that underscore "as is", no?

**Comment by maliknajjar** [comment]
yes I agree. because the "_" wildcard works only when used with the LIKE keyword. so how about escaping the underscore when the LIKE keyword is used?

**Comment by joebordes** [comment]
yes, correct. that is the idea. I shared a link to the QG code section where starts/ends/contains are, there are probably some others there that need that escape

**Comment by maliknajjar** [comment]
ok, I will add it to them too

**Comment by joebordes** [comment]
LGTM. I'll wait to see the unit tests before merging. Ok?

**Comment by maliknajjar** [comment]
yes .. I will create them

**Comment by joebordes** [comment]
thanks!

**Pull request merged**
