### PR TITLE
Fixes dropdownmenus at the wrong top level

### PR DESCRIPTION
**Pull request by Luke1982**
Sorry, github still takes ALL commits (even the already accepted ones) into any pull request I make. Anyway, it's just about the last one, where I change a function in general.js to make dropdownmenu's set their top to the parent's bottom, in stead of adding 22px hardcoded.

### CODE REVIEW

**Comment by Luke1982** [comment]
This Pull is mostly about some improvements to the general.js functions (in terms of positioning elements) and adding classes and id's to elements for styling

**Comment by joebordes** [comment]
I will look in to it today and get back to you.
To avoid the accumulative commits issue you have to create a new branch for each commit. The idea is that you create a branch, apply a change/commit (or various related commits), you create  a PR from that branch, I merge the PR into coreBOS and then you can delete the branch and pull from coreBOS to the the change.
Creating branches is REALLY easy, fast and has almost no cost in disk space, so create as many as you need.

**Comment by Luke1982** [comment]
Ah, That's a good tip. I thought branches had a more vast and permanent character, but I'll look into this.

**Comment by joebordes** [comment]
I cherry-picked 7 commits
 519c827c5906c011ea2b0c710a9c27921ab79a40
 d78dba4bcd2b1a7f9259528fd68fedae693b8efe
 c633c97aee1d09eeadc5d950dc2551a569a41c5e
 cef45fd95e4cfee3357ca08b1cdc4b513bd2f33f
 f24fa77e1a03250d609c643db2fcf214f3ce9226
 b0e1bf995c3b76cbdccf25e90127b1f159ca465c
 e13c05cb595cb9ff264306b7ce2eff684d2f7838


Thanks!!

**Comment by Luke1982** [comment]
I've created two branches: updateCSS and updateJS. In these I will commit all changes I make during my theme development (in which I will find common UI problems and fix them on the fly). When I think I've made some real progress, I'll create a pull for the entire branch and delete it after it's merged.

**Pull request closed without merging**
