### PR TITLE
Autocomplete feature for uitype2

### PR DESCRIPTION
**Pull request by albertxhani**

### CODE REVIEW

**Comment by joebordes** [comment]
I have tried it. I like what I see, it is looking very good. You are on the right track and I like how the code looks.

 - Why couldn't you use the existing getAutocomplete functionality in ExecuteFunctions?
 - I need an example map to see how it works as my mapping doesn't capture the field value

This is the map I am using (Campaigns_FieldInfo):

```
<map>
  <originmodule>
    <originname>Campaigns</originname>
  </originmodule>
  <fields>
    <field>
      <fieldname>campaignname</fieldname>
      <features>
        <feature>
          <name>searchmodule</name>
          <value>Products</value>
        </feature>
        <feature>
          <name>searchfields</name>
          <value>productname</value>
        </feature>
        <feature>
          <name>searchcondition</name>
          <value>startswith</value>
        </feature>
        <feature>
          <name>entityfield</name>
          <value>productname</value>
        </feature>
        <feature>
          <name>showfields</name>
          <value>productname,productcode</value>
        </feature>
        <feature>
          <name>fillfields</name>
          <value>campaignname=productname</value>
        </feature>
      </features> 
   </field>
    <field>
      <fieldname>sponsor</fieldname>
      <features>
        <feature>
          <name>searchmodule</name>
          <value>Vendors</value>
        </feature>
        <feature>
          <name>searchfields</name>
          <value>vendorname</value>
        </feature>
        <feature>
          <name>searchcondition</name>
          <value>startswith</value>
        </feature>
        <feature>
          <name>entityfield</name>
          <value>vendorname</value>
        </feature>
        <feature>
          <name>showfields</name>
          <value>vendorname,email</value>
        </feature>
        <feature>
          <name>fillfields</name>
          <value>sponsor=vendorname</value>
        </feature>
      </features> 
   </field>
  </fields>
</map>
```

I set the uitype of the sponsor field to 2 for testing.

This is how it looks:

autocomplete01

but when I select a value it doesn't fill in the value.

Thanks!

**Comment by albertxhani** [comment]
- The reason didn't use the existing getAutocomplete function is that I needed the return fields values to be mapped with the field values names. the current getAutocomplete returns something like this crmname: 'val1,val2,val3'. Althought I think I can find a workaround with JavaScript

- This is the map I used for testing, you need to have the entityfield added to showfields too.

```
<map>
   <fields>
      <field>
         <fieldname>potentialname</fieldname>
         <features>
            <feature>
               <name>searchmodule</name>
               <value>Contacts</value>
            </feature>
            <feature>
               <name>searchfields</name>
               <value>firstname,lastname</value>
            </feature>
            <feature>
               <name>searchcondition</name>
               <value>startswith</value>
            </feature>
            <feature>
               <name>entityfield</name>
               <value>firstname</value>
            </feature>
            <feature>
               <name>showfields</name>
               <value>firstname,email,mailingstreet</value>
            </feature>
            <feature>
               <name>fillfields</name>
               <value>leadsource=leadsource,assigned_user_id=assigned_user_id,closingdate=support_end_date</value>
            </feature>
         </features>
      </field>
   </fields>
</map>
```

-  I don't know if you noticed  getFieldAutocomplete function in CustomerPortalWS.php had an issue with retrieving fields that have their label name different from the column name https://github.com/tsolucio/corebos/pull/152/commits/d8d3f22ccf3c5e6c10e5b67d979bf1e298b900ec

**Comment by joebordes** [comment]
- ok, I understand, it is fine like that, I was just curious
- works perfectly
- no, I hadn't noticed. I did fix a problem there with vendors module though

Give me a little more time to review it again and I will get back to you, thanks!!

**Comment by albertxhani** [comment]
- This is the map i used for testing

```
<map>
    <originmodule>
        <originname>Potentials</originname>
    </originmodule>
    <fields>
        <field>
            <fieldname>related_to</fieldname>
            <features>
                <feature>
                    <name>searchmodule</name>
                    <value>Contacts</value>
                </feature>
                <feature>
                    <name>searchfields</name>
                    <values>
                        <value>
                            <module>Accounts</module>
                            <value>accountname</value>
                        </value>
                        <value>
                            <module>Contacts</module>
                            <value>firstname,lastname</value>
                        </value>
                    </values>
                </feature>
                <feature>
                    <name>searchcondition</name>
                    <value>startswith</value>
                </feature>
                <feature>
                    <name>entityfield</name>
                    <values>
                        <value>
                            <module>Accounts</module>
                            <value>accountname</value>
                        </value>
                        <value>
                            <module>Contacts</module>
                            <value>firstname</value>
                        </value>
                    </values>
                </feature>
                <feature>
                    <name>showfields</name>
                    <values>
                        <value>
                            <module>Accounts</module>
                            <value>accountname,phone,email1</value>
                        </value>
                        <value>
                            <module>Contacts</module>
                            <value>firstname,email,mailingstreet</value>
                        </value>
                    </values>
                </feature>
                <feature>
                    <name>fillfields</name>
                    <values>
                        <value>
                            <module>Accounts</module>
                            <value>forecast_amount=annual_revenue</value>
                        </value>
                        <value>
                            <module>Contacts</module>
                            <value>leadsource=leadsource,assigned_user_id=assigned_user_id,closingdate=support_end_date</value>
                        </value>
                    </values>
                </feature>
            </features>
        </field>
        <field>
            <fieldname>potentialname</fieldname>
            <features>
                <feature>
                    <name>searchmodule</name>
                    <value>Contacts</value>
                </feature>
                <feature>
                    <name>searchfields</name>
                    <value>firstname,lastname</value>
                </feature>
                <feature>
                    <name>searchcondition</name>
                    <value>startswith</value>
                </feature>
                <feature>
                    <name>entityfield</name>
                    <value>firstname</value>
                </feature>
                <feature>
                    <name>showfields</name>
                    <value>firstname,email,mailingstreet</value>
                </feature>
                <feature>
                    <name>fillfields</name>
                    <value>leadsource=leadsource,assigned_user_id=assigned_user_id,closingdate=support_end_date</value>
                </feature>
            </features>
        </field>
    </fields>
</map>
```

**Comment by joebordes** [comment]
@albertxhani this is working very nicely. Thank you!!

I will discuss a little on gitter about what uitypes to support besides uitype2, but this is already incorporated into the master branch and we will finish anything that comes up there.

 Wonderful!

**Pull request merged**
