### PR TITLE
feat(PageHeader) Convert pageheader to sticky LDS version

### PR DESCRIPTION
**Pull request by Luke1982**
One issue already is that when you add an announcement in chrome, the entire lower part of the pageheader is empty.

### CODE REVIEW

**Comment by Luke1982** [comment]
Also, during editing, the 'edit' and 'save' buttons can also be moved into the page header. At least the top two

**Comment by Luke1982** [comment]
Still have an issue when inline-editing. The header height is not taken into account.

**Comment by Luke1982** [comment]
TODO need to do the 'this record had been removed' message

**Comment by Luke1982** [comment]
TODO, take preheader into account https://github.com/tsolucio/corebos/blob/master/Smarty/templates/Header.tpl#L290-L292

**Comment by joebordes** [comment]
THANK YOU !!!

Incredible :-D

**Pull request merged**
