### PR TITLE
feat(expression) support expression inside strings

### PR DESCRIPTION
**Pull request by maliknajjar**
## Support expression inside strings

You can use curly brackets  `{ expression }` to write valid expressions inside strings. This feature made for long string parameters like the condition parameter of the aggregation function. That parameter supports selecting uitype10 fields but it does not support the usage of normal expression functions.
Inspired by javascript [Template Literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)

### Features
* Works inside strings
* Supports nesting
* Works outside strings too (similar to a Preprocessor in c/c++)

### Examples
image
image
image
image

### CODE REVIEW

**Comment by joebordes** [comment]
This is awesome!!  Not only the idea which makes the expression a lot easier but the simplicity of the implementation. Great job!

I have one issue which is the election of symbols. The opening and closing keys are relatively standard and can conflict in some workflows, especially for web services workflow tasks, but also we use these in GenDoc and they will not work correctly in the {expression} directive (an edge case but valid). Can we change them to something else? backticks or some others?

**Comment by maliknajjar** [comment]
what about normal brackets `[ expression ]`or two curley brackets `{{ expression }}`? 
the problem with backticks `` `expression` `` is that its hard to notice or read sometimes.

**Comment by maliknajjar** [comment]
or we can start it with a dollar sign `${ expression }` or a hashtag `#{ expression }`

**Comment by joebordes** [comment]
Thanks!

**Pull request merged**
